accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # django에서는 회원정보 수정 시 비번 수정 기능을 제공하지 않기에 password를 따로 구현해야 함
    path('password/', views.password, name='password'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # follow url
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),

    # 좋아요
    path('<int:article_pk>/like/', views.like, name='like'),

    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

    # comment url 만들기
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),

    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('', views.index, name='index'),
    # create url 만들기
    path('create/', views.create, name='create'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    # articles/로 들어오면 게시글 내용 제공한다
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models
from django.conf import settings  # setting에 기본 저장되어 있는 user model 불러오는 작업

# article.liked_users.all()
# user.liked_articles.all()
# article.user을 쓸 수 있게 됨 (user의 Foreignkey 설정)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # auto_now_add 데이터가 추가될 때마다 자동으로 시간 넣어줌
    updated_at = models.DateTimeField(auto_now=True)

    # 한명의 USER가 article을 여러개 작성한다 (M:N)
    # USER 정보가 없어지면, Article 정보도 없어진다.
    # 다른 모든 곳에서는 get_user_model로 가져오되, models.py에서 user을 가져올 땐 django setting의
    # default 된 user model을 가져와야 함
    # AUTH_USER_MODEL 을 기억해야함★★★★
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 좋아요 누른 유저
    liked_users = models.ManyToManyField(  # article.liked_users.all() => 아티클을 좋아하는 모든 유저
        settings.AUTH_USER_MODEL, 
        related_name='liked_articles',) # user.liked_articles.all() => 유저가 좋아하는 모든 아티클 유저)

    class Meta:
        ordering = ('-pk', )

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # article 참조키(foreign key)
    # relatedname은 나중에 views.py>detail 에서 comments = article.comments.all()
    # article.comment_set.all()로 받아와야 하지만,
    # related_name 설정을 통해 article.comments.all()로 가져올 수 있게 됨
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # article 에 포함된 meta data가 작성되는 것
    class Meta:
        model = Article
        # form에서 all 필드 설정하면 user form까지 보임
        # 모든 필드를 선택하는 것이 아닌, title과 content만 보이게!
        fields = ['title', 'content', ]

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='comment',
        )
    class Meta:
        model = Comment
        # fields를 all로 하면, article 선택창이 뜸
        fields = ['content', ]
        # exclue = ['article', ] 로 해도 됨

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404  # redirect 추가
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse, JsonResponse
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from IPython import embed 


@require_GET
def index(request):
    # embed()
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

@require_GET
def detail(request, article_pk):
    # 사용자가 url에 적어보낸 article_pk를 통해 디테일 페이지 보여준다
    # article 있다면 하나 꺼내서 보여주고 없으면 404 페이지 보여줌
    article = get_object_or_404(Article, pk=article_pk)
    # commentform에 맞는 form 형식받는 것;get
    form = CommentForm()
    # 해당 article pk 에 있는 comments를 모두 가져온다
    comments = article.comments.all()
    # 혹은, comments = Comment.objects.all()로도 사용함
    # 혹은, comments = article.comment_set.all()
    
    # context에 담아야 templates로 보낼 수 있으니까, context 작업
    context = {
        'article': article,
        'form': form,
        'comments': comments,
        }
    return render(request, 'articles/detail.html', context)
    # return render(request, 'article/detail.html', {'article': article})
    # 이렇게 나와도 전혀 상관없음(틀린게 아님!)

# 로그인 된 상태에서만 CREATE 실행
@login_required  # get요청으로 감
def create(request):
    # 만약 사용자가 보낸 method가 POST(Article을 생성해달라고 하는 요청)
    if request.method == 'POST':
        form = ArticleForm(request.POST)  # 여기로 들어오는 건 title, content
        # embed()  # 실행중 python shell 실행
        if form.is_valid():  # 유효하다면, 이 땐, title 과 content가 valid 한지 판별
            article = form.save(commit=False)  # article을 바로 db에 반영하지 않고 
            article.user = request.user # 로그인 된 유저 정보를 생성하려고 하는 ariticle user 정보로 넣겠다 
            article.save()
            return redirect('articles:detail', article.pk)
        # else:  # 유효하지 않다면,(ex. 20자짜리인데 200자가 들어간 경우,))
        #     context = {'form': form}
        #     return render(request, 'articles/create.html', context)

    else:  # GET이면, Article을 생성하기 위한 페이지 달라고 하는 요청
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)

@login_required  # get 요청 있는 경우에만 login_required 가능
# /articles/3/update
def update(request, article_pk):
    # 3번 article을 update할 때 있으면 수정, 아니면 404 보여주기
    article = get_object_or_404(Article, pk=article_pk)
    # get일 때와 post일 때 나눠서 작업해야함

    # article 작성자인 경우에만 update 가능하게 하는 작업
    if article.user == request.user:
        # POST 로 들어오면 UPDATE 로직을 수행한다
        if request.method == 'POST':
            # model form 활용
            # 기존에 받은 instance(article)을 form에 추가한다
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
    
        else:  # get
            # model form 활용
            # form에 아무것도 넣지 않으면 빈칸으로 form이 보여짐
            # instance에 article을 넣으면, article에 있던 내용이 저장된 채로 보여짐
            form = ArticleForm(instance=article)  # form 안에 특정 article 담아서 생성하겠다
            # 위에서 정의한 form을 context로 넘겨줌
    else:
        return redirect('articles:detail', article_pk)
    context = {'form': form}
    return render(request, 'articles/update.html', context)


# login_required 는 get 요청에만 가능하므로 POST에는 쓸 수 없음
# @login_required
# /articles/3/delete/
@require_POST
def delete(request, article_pk):
    # 함부로 delete 하지 못하게 하기 위해 POST method 해줘야 함

    if request.user.is_authenticated:
    # article_pk에 맞는 article을 꺼내서 삭제함
    # 삭제할 article 꺼내는 작업
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
        # article 이 있다면(no 404 page) 삭제
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')


# detail 페이지에서 다 처리할 것이기 때문에 get이 따로 없으므로
# require_POST 처리함
# @login_required ; post ㄴㄴ 
@require_POST
def comments_create(request, article_pk):
    # 사용자가 로그인 되었을 때에만
    if request.user.is_authenticated:
        form = CommentForm(request.POST)

        if form.is_valid():
            # 완전히 db에 반영하지는 말자 commit=False(임시저장)
            comment = form.save(commit=False)
            comment.article_id = article_pk
            # 이 작업이 끝나면 comment에 content와 id가 다 들어가고, 그걸 저장한다
            comment.user = request.user 
            comment.save()            
        # 유효하든, 유효하지않든 이 화면 보여준다
    return redirect('articles:detail', article_pk)


# @login_required
@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        article = get_object_or_404(Article, pk=article_pk)
        # 로그인한 사람이랑 코멘트 단 사람 같으면,
        if comment.user == request.user or article.user == request.user:
            comment.delete()
    # article = get_object_or_404(Article, pk=article_pk) 안했으니까
    # article.pk 못씀
        return redirect('articles:detail', article_pk)
        
    # 401 code == 인증되지 않았다
    # 이 설정 후, 쿠키>session 삭제하면, 로그아웃이 되고, 그 상태에서 댓글 삭제를 하면 
    # 401 페이지와 함께 you are Unauthorized 가 출력됨
    return HttpResponse('You are Unauthorized', status=401)


def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)

    # if user in aricle_liked_users.all(): 과 바로 밑 한 줄과 같음
    if article.liked_users.filter(pk=user.pk).exists():  # 1개 데이터라도 존재하면 True
            user.liked_articles.remove(article)
            liked = False
    else:
        user.liked_articles.add(article)
        liked = True
    context = {
        'liked': liked,
        'count': article.liked_users.count(),  # article을 좋아요 한 유저
    }
    # return redirect('articles:detail', article_pk)
    return JsonResponse(context)  


@login_required
# user_pk == 팔로우 할 대상
def follow(request, article_pk, user_pk):
    # 로그인 한 유저가 게시글 유저를 follow or unfollow 하는 기능 구현
    # 로그인 유저 가져오는 작업(요청 보내는 유저)
    user = request.user
    # 게시글 작성한 유저 가져오는 작업(팔로우/언팔로우 할 사람)
    person = get_object_or_404(get_user_model(), pk=user_pk)  # 게시글 주인
    # get_user_model 하려면 상단에서 import 해야 함

    # 지금 로그인한 사람이 게시글을 쓴 사람의 follow 목록에 있다면,
    # == 이미 팔로우 상태에서 팔로우 한 번 더 누르는 거
    # == 언팔
    if user in person.followrs.all():
        person.followers.remove(user)  # 언팔
    else:  # 팔로우 상태가 아니면,
        person.followers.add(user)  # 팔로우한다

    # article_pk 가져와야 어느 게시글에서 받아서 어느 게시글에 보내줄 지 알 수 있음    
    return redirect('articles:detail', article_pk)

articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ article.user.username }}</h1>
  <hr>
  <p class="lead">
    팔로잉: {{ article.user.followings.all|length }} 명 /
    팔로워: {{ article.user.followers.all|length }} 명
  </p>

{% comment %} 본인이 본인을 팔로우 하지 못하게 하는 설정함 {% endcomment %}
  {% if user != article.user %}
    {% if user in article.user.followers.all %}
    {% comment %} 언팔버튼 {% endcomment %}
    <a href=" {% url 'articles:follow' article.pk article.user.pk %} " class="btn btn-primary btn-lg">Unfollow</a>
    {% else %}
    {% comment %} 팔로우버튼 {% endcomment %}
    <a href=" {% url 'articles:follow' article.pk article.user.pk %} " class="btn btn-primary btn-lg">follow</a>
    {% endif %}
  {% endif %}

</div>

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %} Article: Create{% endblock title %}

{% comment %} 
POST요청으로 보내면 url은 동일한데 method만 다르게(/articles/create/) 
{% endcomment %}
{% block container %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  {% comment %} <input type="text"><br>
  <textarea name="" cols="30" rows="10"></textarea><br> {% endcomment %}
  <button type="submit">생성하기</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article: detail{% endblock title %}

{% block container %}
{% comment %} url + app name + index page {% endcomment %}
  {% comment %} <a href="{% url 'articles:index' %}">[목록]</a>  {% endcomment %}
  <h2>{{ article.title }}</h2>
  <p>{{ article.created_at }}</p>
  <p class="text-secondary"> 작성자: {{ article.user }}</p>
  <hr>

{% comment %} 좋아요 구현 {% endcomment %}
  {% comment %} <a href=" {% url 'articles:like' article.pk %} "> {% endcomment %}
  {% comment %} 좋아요를 눌렀다면, {% endcomment %}
  {% comment %} {% if user in article.liked_users.all %}
  <i class="fas fa-heart fa-lg" style="color: pink"></i>  
  {% else %}
  <i class="far fa-heart fa-lg" style="color: pink"></i>
  {% endif %}
  </a> {% endcomment %}


  {% comment %} js 활용한 좋아요 구현 {% endcomment %}
  <i
   class=" {% if user in article.liked_users.all %}fas{% else %}far{% endif %} fa-heart fa-lg" 
   id="like-btn" 
   data-id="{{ article.pk }}"
   style="color: red"
   >
   </i>

  {% comment %} <span class='text-success'>{{ article.liked_users.all | length }} 명이 이 글을 좋아합니다!</span> {% endcomment %}
  <p> <span id="like-count" class='text-success'>{{ article.liked_users.all | length }}</span>명이 이 글을 좋아합니다</p>
  <hr>
  <p>{{ article.content }}</p>
  <hr>

  
  {% comment %} 작성자 == 로그인한 유저일 때에만 수정하기 버튼이 보임 {% endcomment %}
  {% if article.user == request.user %}
  <a href=" {% url 'articles:update' article.pk %} ">[수정하기]</a>
  <hr>
  {% endif %}
 

  {% if article.user == request.user %}
  {% comment %} /articles/3/delete/로 보내야 하니까 action {% endcomment %}
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">삭제하기</button>
  </form>
  <hr>
  {% endif %}


  {% comment %} comment 작성 {% endcomment %}
  {% if user.is_authenticated %}
  <form action=" {% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="btn btn-warning text-white">댓글쓰기</button>
  </form>
  {% else %}
  <a href=" {% url 'accounts:login' %} ">댓글작성은 로그인 후 가능합니다</a>
  {% endif %}
  <hr>


  {% comment %} 댓글표시 {% endcomment %}
  <ul>
  {% for comment in comments %}
    <li>
      {% if request.user == comment.user or request.user == article.user %}
      <form method="POST" action=" {% url 'articles:comments_delete' article.pk comment.pk %} ">
        {% csrf_token %}
        <p>
        <span class="text-secondary">
        [{{ comment.user }}]{{ comment.content }} ({{ comment.created_at }})
        </span> 
        <button type="submit" class="btn btn-link">삭제하기</button>
        </p>
      </form>
      {% comment %} 로그인이 안 되어 있으면 내용만 보여준다 {% endcomment %}
      {% else %}
      <span>[{{ comment.user }}] {{ comment.content }} ({{ comment.created_at }})</span>
      {% endif %}
    </li>
  {% endfor %}
  </ul>

{% comment %} articles/_follow에 있는 html 가져와주세요! {% endcomment %}
{% include 'articles/_follow.html' %}

<script>
  const likeButton = document.querySelector('#like-btn')
  likeButton.addEventListener('click', () => {
    console.log(event)

    // Button 의 data-id 속성을 아래 코드로 가지고 온다
    const articleId = event.target.dataset.id

    axios.get(`/articles/${articleId}/like/`)
    .then(function(response){
      // console.log(response)

      // 사용자의 좋아요 여부에 따라 버튼 클래스 변경
      if(response.data.liked) {
        // console.log(likeButton.classList)
        likeButton.classList.remove('far')
        likeButton.classList.add('fas')
        } else {
        likeButton.classList.remove('fas')
        likeButton.classList.add('far')
        }

        // article을 좋아하는 사람들의 데이터 수를 응답받아 적용
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.count
      
    })
  })

</script>
{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Article: Index{% endblock title %}

{% block container %}
  <h2>Article list</h2>

  {% if user.is_authenticated %}
  <a href="{% url 'articles:create' %}">[생성하기]</a>
  {% else %}
  <p> 회원가입 후 게시글을 작성해 주세요!</p>
  <a href=" {% url 'accounts:signup' %} ">회원가입하기</a>
  {% endif %}
  <hr>
  
  {% for article in articles %}
  <div>
    <h3>{{ article.pk }}. {{ article.title }}</h3>
    <p class="text-secondary"> 작성자: {{article.user}} </p>
    {% comment %} article:detail 페이지로 넘어간다. {% endcomment %}
    <a href=" {% url 'articles:detail' article.pk %} ">[상세보기]</a>
  </div>
  <br>
  {% endfor %}
{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %} Article: Update{% endblock title %}

{% block container %}
<form method="POST" action="{% url 'articles:create' %}" >
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">수정하기</button>
</form>
{% endblock container %}