accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # django에서는 회원정보 수정 시 비번 수정 기능을 제공하지 않기에 password를 따로 구현해야 함
    path('password/', views.password, name='password'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # follow url
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),

    # 좋아요
    path('<int:article_pk>/like/', views.like, name='like'),

    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

    # comment url 만들기
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),

    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('', views.index, name='index'),
    # create url 만들기
    path('create/', views.create, name='create'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    # articles/로 들어오면 게시글 내용 제공한다
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  {% comment %} 직접 bootstarp 가져오기 {% endcomment %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

  {% comment %} fontawesome 가져오기 {% endcomment %}
  <script src="https://kit.fontawesome.com/23ba31e91b.js" crossorigin="anonymous"></script>

  {% comment %} axios 가져오기 {% endcomment %}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <title>{% block title %}{% endblock title %}</title>
</head>

<body>
  <header class="container">
    <h1 class="text-secondary"><span class="text-primary">페이지</span>에 오신 걸 환영합니다:)</h1><br>

    {% comment %} 로그인이 되었다면, {% endcomment %}
    {% if user.is_authenticated %}
    {% comment %} user은 templates 가 기본적으로 가지고 있는 것이므로 따로 정의 안해도 사용 가능함 {% endcomment %}
    <h2>안녕하세요,  <span class="text-success">{{ user.username }}</span>님!</h2><br>
    <p>
    <a href="{% url 'accounts:logout' %}" >로그아웃</a>
    <a href=" {% url 'accounts:update' %} ">회원정보수정</a>
    </p>

    <form action=" {% url 'accounts:delete' %} " method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-success">회원탈퇴</button>
    </form>
    <hr>
    {% comment %} 로그인 된 상태가 아니면, {% endcomment %}
    {% else %}  
    <p>
    <a href=" {% url 'accounts:login' %} " >로그인</a>
    <a href=" {% url 'accounts:signup' %} ">회원가입</a>
    </p>
    {% endif %}

    <a href="{% url 'articles:index' %}">[홈 화면]</a> 
    <hr>
  </header>

  <div class="container">
  {% block container %}{% endblock container %}
  </div>


  {% comment %} js 가져오기 {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src=" {% static 'bootstrap/js/bootstrap.bundle.min.js' %} "></script>
</body>
</html>